DROP table exhibition;
CREATE TABLE EXHIBITION(EXNO INTEGER,TITLE VARCHAR2(500),DESCRIPTION VARCHAR2(500),ISVIRTUAL VARCHAR2(500),ORGANIZER VARCHAR2(500));
DROP table EX_CONTENT;
CREATE TABLE EX_CONTENT(WORK INTEGER,EXHIBITION INTEGER, ORG_COMMENT VARCHAR2(500));
DROP table WORK;
CREATE TABLE WORK(WNO INTEGER,AUTHOR INTEGER,TITLE VARCHAR2(500),SUPPORT VARCHAR2(500),C_DATE VARCHAR2(500),HEIGHT VARCHAR2(500),WIDTH VARCHAR2(500),ACQUIRED VARCHAR2(500),TEXT VARCHAR2(500),AUDIO VARCHAR2(500),PICTURE VARCHAR2(500),MOVIE VARCHAR2(500));
DROP table ART_CNTY;
CREATE TABLE ART_CNTY(ARTIST INTEGER,COUNTRY VARCHAR2(500),TYPE VARCHAR2(500));
DROP table MUSEUM;
CREATE TABLE MUSEUM(MNO INTEGER,NAME VARCHAR2(500),CITY VARCHAR2(500),COUNTRY VARCHAR2(500),URL VARCHAR2(500));
DROP table OWNERSHIP;
CREATE TABLE OWNERSHIP(WORK INTEGER,MUSEUM INTEGER);
DROP table ARTISTB;
CREATE TABLE ARTISTB(ANO INTEGER,NAME VARCHAR2(500),BIRTHDATE VARCHAR2(500),DEATHDATE VARCHAR2(500));
DROP table artist;
CREATE TABLE ARTIST(ANO INTEGER,NAME VARCHAR2(500),BIRTHDATE INTEGER,DEATHDATE INTEGER);
--
CREATE SEQUENCE MW_SEQ
--
insert into lazy_rolenode values ('PUBLIC','exhibition','TABLE','NO','999','nodef');
insert into lazy_rolenode values ('PUBLIC','ex_content','TABLE','NO','999','nodef');
insert into lazy_rolenode values ('PUBLIC','work','TABLE','NO','999','nodef');
insert into lazy_rolenode values ('PUBLIC','art_cnty','TABLE','NO','999','nodef');
insert into lazy_rolenode values ('PUBLIC','artist','TABLE','NO','999','nodef');
