#!/bin/sh
# make the lazy SQL compiler
javac Compiler.java lc.java \
-classpath .:$TOMCAT_HOME/lib/servlet.jar:\
$TOMCAT_HOME/common/lib/servlet.jar:\
$TOMCAT_HOME/webapps/lazy/WEB-INF/classes \
-d $TOMCAT_HOME/webapps/lazy/WEB-INF/classes

