#!/bin/sh

CP=.:$TOMCAT_HOME/lib/servlet-api.jar:$TOMCAT_HOME/common/lib/servlet.jar:$TOMCAT_HOME/webapps/lazy/WEB-INF/classes

# ADD Jena lib
for j in ${JENA_LIB}/* ; do
    CP=${CP}:$j
done

javac ns.java -classpath $CP -d $TOMCAT_HOME/webapps/lazy/WEB-INF/classes

