#!/bin/sh
CP=.:$TOMCAT_HOME/lib/servlet.jar::$TOMCAT_HOME/lib/servlet-api.jar:\
$TOMCAT_HOME/common/lib/servlet.jar:\
$TOMCAT_HOME/webapps/lazy/WEB-INF/classes
# ADD Jena lib
for j in ${JENA_HOME}/lib/* ; do
    CP=${CP}:$j
done
# echo $CP
javac tsp.java -classpath ${CP} 

